name: Build and deploy dotnet core app to Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x' # set this to the dotnet version to use
  OUTPUT_PATH: ${{ github.workspace }}/myfunc

jobs:
  build_function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: ouput path
        shell: bash
        run: echo ${{ env.OUTPUT_PATH }}
        
      - name: Publish functions
        run: dotnet publish --configuration Release --output ${{ env.OUTPUT_PATH }}

      - name: Package functions
        uses: actions/upload-artifact@v2
        with:
          name: functions
          path: ${{ env.OUTPUT_PATH }}

      - name: Uploading tools folder
        uses: actions/upload-artifact@v2
        with:
          name: builds
          path: Tools

  deploy:
    runs-on: windows-latest
    needs: ["build_function"]
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: ouput path
        shell: bash
        run: echo ${{ env.OUTPUT_PATH }}

      - name: Download function artifacts
        uses: actions/download-artifact@v1
        with:
          name: functions
          path: ${{ env.OUTPUT_PATH }}

      - name: Download function artifacts
        uses: actions/download-artifact@v1
        with:
          name: builds
          path: ${{ env.OUTPUT_PATH }}
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_AD_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_AD_CLIENT_SECRET}}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_AD_TENANT_ID }}"}'
          enable-AzPSSession: true

      - name: Enable JIT access for publishing
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ env.OUTPUT_PATH }}\ConfigureJIT.ps1 -WebAppName SanderLindberg-func -ResourceGroupName AZ-SanderLindberg-APIM-Apis-rg -RuleName "Pipeline" -Enable $true
          azPSVersion: "latest"
          
      - name: Run Azure Functions Action
        uses: azure/functions-action@v1
        with:
          app-name: ${{ steps.infrastructure.outputs.function-app-name }}
          package: ${{ env.OUTPUT_PATH }}
      
      - name: Disable JIT access for publishing
        if: ${{ always() }}
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ env.OUTPUT_PATH }}\ConfigureJIT.ps1 -WebAppName SanderLindberg-func -ResourceGroupName AZ-SanderLindberg-APIM-Apis-rg -RuleName "Pipeline" -Enable $false
          azPSVersion: "latest"
